### ISSUE TITLE
memory access out of bound

### ISSUE THREAD

**Issue by bidinzky** [IFCjs/web-ifc-three#21]
Hello as mention in the title with the file in
[Duplex Apartment.zip](https://github.com/agviegas/web-ifc-three/files/6630916/Duplex.Apartment.zip) causes a memory out of bounds exception.
`
Uncaught RuntimeError: memory access out of bounds
    at http://localhost:5000/web-ifc.wasm:wasm-function[930]:0x4f3a4
    at http://localhost:5000/web-ifc.wasm:wasm-function[931]:0x4ff87
    at Object.GetLine (eval at new_ (http://localhost:5000/bundle.js:1:1), <anonymous>:9:10)
    at IfcAPI.GetRawLineData (http://localhost:5000/bundle.js:36157:28)
    at IfcAPI.GetLine (http://localhost:5000/bundle.js:36109:28)
    at IfcLoader.getItemProperties (http://localhost:5000/bundle.js:70365:29)
    at HTMLCanvasElement.selectObject (http://localhost:5000/bundle.js:72048:29)
(anonymous) @ web-ifc.wasm:0x4f3a4
(anonymous) @ web-ifc.wasm:0x4ff87
GetLine @ VM354:9
GetRawLineData @ web-ifc-api.js:45366
GetLine @ web-ifc-api.js:45318
getItemProperties @ IfcLoader.js:128
selectObject @ web-ifc-scene.js:114
`

I am not really sure if its a problem with the usage of the web-ifc api or the api itself.

Edit.: it only happens when you try to select specific parts of the model (e.g. parts of the roof)

**Comment by CrossStyle** [comment]
Hello,

I had a similar problem when I tried to open an [IFC file ](https://github.com/CrossStyle/BIM-Viewer/blob/8eb69a0f2c928b251404ffa1d502942214c8e2db/local_app/9-6TH%20FLOOR.ifc) that was part of a model.

```
RuntimeError: memory access out of bounds
    at web-ifc.wasm:0x8196
    at web-ifc.wasm:0x33d3b
    at web-ifc.wasm:0x1f7db
    at Object.LoadAllGeometry (eval at new_ (bundle.js:3694), <anonymous>:8:10)
    at IfcAPI.LoadAllGeometry (bundle.js:36194)
    at IFCParser.saveAllPlacedGeometriesByMaterial (bundle.js:70403)
    at IFCParser.loadAllGeometry (bundle.js:70349)
    at IFCParser.parse (bundle.js:70332)
    at async Object.onLoad (bundle.js:70834)
```

**Comment by agviegas** [comment]
Hey @bidinzky I am able to open and select part of the roofs in the [last version](https://agviegas.github.io/web-ifc-three/example/). Can you check it? @CrossStyle I'll take a look at this!

**Comment by agviegas** [comment]
@CrossStyle it looks like this happens in web-ifc. Can you bring this issue there? Thanks!

**Comment by loubna-tech** [comment]
@CrossStyle have you managed to fix the issue?
