### ISSUE TITLE
"Uncaught (in promise) TypeError: this context is undefined" in prePickIfcItem

### ISSUE THREAD

**Issue by m1900** [IFCjs/web-ifc-three#95]
I keep getting the mentioned error in my application based on this post [https://ifcjs.github.io/info/blog/Build%20a%20CDE%20in%2030%20minutes/ ](https://ifcjs.github.io/info/blog/Build%20a%20CDE%20in%2030%20minutes/ ) (I left out the Google Drive part and select an IFC using a simple input element instead). Version of web-ifc-viewer used is 1.0.168.

An extract of my code can be found in my [ProtoIfcViewer repo](https://github.com/m1900/ProtoIfcViewer.git).

**Comment by m1900** [comment]
This issue actually belongs to [web-ifc-viewer](https://github.com/IFCjs/web-ifc-viewer) but I don't have the right to transfer it.

**Comment by simplynail** [comment]
Hi @m1900 , I'm getting similar error when basing my code on "google drive CDE" blog post but for local drive ifc file selection.
I'm passing `ifcfile = event.target.files[0]` to `window.webIfcAPI.IFC.loadIfc(ifcfile)` (I'm using "test.ifc" file from "examples")
and I get:
```       
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prePickIfcItem')
       at prePickIfcItem (main.js:91596:33)
       prePickIfcItem @ main.js:91596
 ```

```       
       Error loading IFC. @ main.js:91516
```

```
    RuntimeError: null function or function signature mismatch @ main.js:91517
    at web-ifc.wasm:0x3bc26
    at Module.___errno_location (main.js:49936:94)
    at setErrNo (main.js:49475:22)
    at _clock_gettime (main.js:49485:17)
    at web-ifc.wasm:0x25cfb
    at Module.___wasm_call_ctors (main.js:49918:96)
    at func (main.js:49913:15)
    at callRuntimeCallbacks (main.js:45769:19)
    at initRuntime (main.js:45607:15)
    at doRun (main.js:50012:17)
```
